name: Keepalive

on:
  # The 4th of every month at 9:20am UTC
  schedule:
    - cron: '20 9 4 * *'
  workflow_dispatch:

jobs:
  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    steps:
      - name: Keepalive
        uses: silverstripe/gha-keepalive@v1
